## Tutorial 8_python Numpy Arrays

## Numpy Tutorials
Numpy is a general arry processing pakage.it provides a high performance multidimensionl arry object,
and tools for working with these arrays. it is the fundamental pakage for scientific with python

## What is an array 
An array is a data structure that stores values of same data type in python this is the main difference between list while python list can contion values corresponding to different data type arrays in python can only contain values corresponding to same tye

In [36]:
## import the library
import numpy as np

In [37]:
lst = [1,2,3,4]
arr = np.array(lst)
type(arr)

numpy.ndarray

In [38]:
lst1 = [1,2,3,4]
lst2 = [1,2,3,4]
lst3 = [1,2,3,4]
arr1 = np.array([lst1,lst2,lst3])

In [39]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [40]:
arr1.shape

(3, 4)

In [41]:
arr

array([1, 2, 3, 4])

In [42]:
# indexing 
arr[0]

np.int64(1)

In [43]:
arr[0]=5

In [44]:
arr

array([5, 2, 3, 4])

In [45]:
arr[1:3]

array([2, 3])

In [46]:
arr[:-1]

array([5, 2, 3])

In [47]:
arr[-1]

np.int64(4)

In [48]:
arr[::-2]

array([4, 2])

In [49]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [51]:
arr1[:,1]

array([2, 2, 2])

In [54]:
arr1[1:,1:3]

array([[2, 3],
       [2, 3]])

In [56]:
 arr1[1:,2:]

array([[3, 4],
       [3, 4]])

In [57]:
 # EDA
arr

array([5, 2, 3, 4])

In [71]:
arr[arr<2]

array([], dtype=int64)

In [73]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [76]:
arr1.reshape(4,3)

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4]])

In [81]:
### mechanism to create an arry
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [82]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [85]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [86]:
arr1 * arr1

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 16]])

In [87]:
arr * arr

array([25,  4,  9, 16])

In [88]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [93]:
np.random.randint(10,50,4)

array([13, 42, 12, 16], dtype=int32)

In [94]:
np.random.randint(10,50,4).reshape(2,2)

array([[39, 47],
       [25, 27]], dtype=int32)

In [95]:
np.random.randn(5,6)

array([[ 1.46308662, -1.16125236, -0.50249241, -1.3171567 ,  0.26865065,
         0.06205466],
       [-1.63933579,  1.66108207,  1.73717136,  0.34161247, -0.85495302,
        -0.38613307],
       [-1.79257746, -0.31723391, -0.15335081, -0.90071477,  0.79026169,
         1.07946776],
       [-0.02100921, -0.19030847, -0.08599012,  0.18761521, -2.04853331,
         0.32460324],
       [ 1.00538383,  0.09184632, -0.35775704,  0.75851126, -0.82807814,
        -0.0509721 ]])

In [ ]:
np.random.random_sample